version: '3'
services:
  energy_calculations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy_calculations
    # entrypoint: tail -f /dev/null 
    volumes:
      # this is kinda confusing with the whay the image is created 
      # - ./energy_prices:/app/energy_prices
      - ./energy_prices/daily:/app/energy_prices/daily
      - ./energy_prices/historical:/app/energy_prices/historical
      - ./bills/svgs:/app/bills/svgs
      - ./energy_predictions:/app/energy_predictions
      - ./energy_predictions/daily:/app/energy_predictions/daily
      - ./bills:/app/bills
      - ./in_csv:/app/in_csv
      - ./production_content:/app/production_content
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - TZ=America/Chicago
    # network_mode: host
    ports: 
      - 127.0.0.1:3330:3000
    restart: unless-stopped
