version: '3'
services:
  energy_calculations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy_calculations
    volumes:
      - ${PWD}/energy_prices:/app/energy_prices
      - ${PWD}/bills:/app/bills
      - ${PWD}/in_csv:/app/in_csv
      - ${PWD}/production_content:/app/production_content
      - ${PWD}/energy_prices/daily:/app/energy_prices/daily
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment: 
      - TZ=America/Chicago
    # network_mode: host
    ports: 
      - 127.0.0.1:3330:3000
    restart: unless-stopped
